"""Validate this package against real R output on YOUR data -- not just
the synthetic scenarios in r_reference/.

Everything runs locally (no network calls): this reads whatever file you
point it at, fits both R's coxph() and this package's CoxPH in
subprocesses/in-process on your machine, and writes a comparison report
next to your data. Nothing here is transmitted anywhere, which matters
if the data in question is a real claims extract.

Usage
-----
    python -m pprof_py.diagnostics.survival.validate_against_r --spec my_model.json

See `EXAMPLE_SPEC` below for the JSON shape. A spec describes ONE model
(right-censored or left-truncated, with optional strata/offset/weight)
or the real two-stage SMR/SHR pattern (a `stage1` plus a `stage2` whose
offset is automatically stage 1's fitted linear predictor).

If R + the `survival` package aren't available in this environment (e.g.
a Databricks cluster without R installed), the R-side fit is skipped
automatically -- you still get the preflight diagnostics, the Python
fit, and the generated R script, which you can copy to any machine that
does have R and run there for the comparison this script would otherwise
have done for you (`Rscript run_all_check.R` in the output directory).
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any

import numpy as np
import pandas as pd

from ...models.survival.coxph import CoxPH
from .preflight import preflight_report


EXAMPLE_SPEC = {
    "data": "path/to/your_data.csv",
    "ties": "breslow",
    "output_dir": "validation_output",
    "stage1": {
        "covariates": ["age", "comorbidity_score"],
        "start": "t_start",
        "stop": "t_stop",
        "event": "event",
        "strata": "provider_id",
        "offset": "log_exposure",
        "sample_weight": "wt",
    },
    "stage2": {
        "covariates": [],
        "sample_weight": "wt",
    },
}


@dataclass
class StageSpec:
    covariates: List[str] = field(default_factory=list)
    duration: Optional[str] = None
    start: Optional[str] = None
    stop: Optional[str] = None
    event: Optional[str] = None
    strata: Optional[str] = None
    offset: Optional[str] = None
    sample_weight: Optional[str] = None

    @classmethod
    def from_dict(cls, d: dict) -> "StageSpec":
        known = {f.name for f in cls.__dataclass_fields__.values()}
        return cls(**{k: v for k, v in d.items() if k in known})


def _fit_python(df: pd.DataFrame, spec: StageSpec, ties: str, offset_override=None) -> CoxPH:
    kwargs = dict(event=df[spec.event])
    if spec.start is not None:
        kwargs["start"] = df[spec.start]
        kwargs["stop"] = df[spec.stop]
    else:
        kwargs["duration"] = df[spec.duration or spec.stop]
    if spec.strata is not None:
        kwargs["strata"] = df[spec.strata]
    if offset_override is not None:
        kwargs["offset"] = offset_override
    elif spec.offset is not None:
        kwargs["offset"] = df[spec.offset]
    if spec.sample_weight is not None:
        kwargs["sample_weight"] = df[spec.sample_weight]

    X = df[spec.covariates] if spec.covariates else pd.DataFrame(index=df.index)
    return CoxPH(ties=ties).fit(X, **kwargs)


def _r_formula_rhs(spec: StageSpec, offset_col: Optional[str]) -> str:
    terms = list(spec.covariates)
    if spec.strata is not None:
        terms.append(f"strata({spec.strata})")
    if offset_col is not None:
        terms.append(f"offset({offset_col})")
    return " + ".join(terms) if terms else "1"


def _r_surv_call(spec: StageSpec) -> str:
    stop_col = spec.stop or spec.duration
    if spec.start is not None:
        return f"Surv({spec.start}, {stop_col}, {spec.event})"
    return f"Surv({stop_col}, {spec.event})"


def generate_r_script(
    data_path: str,
    stage1: StageSpec,
    ties: str,
    stage2: Optional[StageSpec] = None,
    results_dir: str = "r_check_results",
) -> str:
    """Build a standalone R script that fits the identical model(s) on
    the identical data file and writes coefficient/log-likelihood/
    baseline-hazard CSVs to `results_dir` -- the same shape this
    package's own r_reference/run_all.R produces, so the comparison
    logic in `compare_with_r` can read either.
    """
    lines = [
        "#!/usr/bin/env Rscript",
        "# Auto-generated by pprof_py.diagnostics.survival.validate_against_r -- do not hand-edit;",
        "# regenerate from the JSON spec instead so the two stay in sync.",
        "suppressMessages(library(survival))",
        f'd <- read.csv("{data_path}")',
        f'results_dir <- "{results_dir}"',
        'dir.create(results_dir, showWarnings = FALSE, recursive = TRUE)',
        "",
        "write_result <- function(fit, name, has_strata=FALSE) {",
        "  s <- summary(fit)",
        "  coefs <- as.data.frame(s$coefficients)",
        "  if (nrow(coefs) > 0) {",
        '    se_col <- grep("^se\\\\(coef\\\\)$", colnames(coefs))',
        "    out <- data.frame(term=rownames(coefs), coef=coefs[[\"coef\"]],",
        "                       se_coef=coefs[, se_col], z=coefs[[\"z\"]])",
        '    write.csv(out, file.path(results_dir, paste0(name, "_coefficients.csv")), row.names=FALSE)',
        "  }",
        '  meta <- data.frame(loglik_beta=fit$loglik[length(fit$loglik)], loglik_null=fit$loglik[1],',
        "                      n=fit$n, nevent=fit$nevent)",
        '  write.csv(meta, file.path(results_dir, paste0(name, "_meta.csv")), row.names=FALSE)',
        "  bh <- basehaz(fit, centered=FALSE)",
        "  if (!has_strata) bh$strata <- \"0\"",
        '  write.csv(bh, file.path(results_dir, paste0(name, "_baseline.csv")), row.names=FALSE)',
        "}",
        "",
        f'fit1 <- coxph({_r_surv_call(stage1)} ~ {_r_formula_rhs(stage1, stage1.offset)}, data=d,',
        f'              ties="{ties}"' + (f", weights={stage1.sample_weight}" if stage1.sample_weight else "") + ")",
        "print(summary(fit1))",
        f'write_result(fit1, "stage1", has_strata={"TRUE" if stage1.strata else "FALSE"})',
    ]

    if stage2 is not None:
        cov_str = ", ".join(f'"{c}"' for c in stage1.covariates)
        lines += [
            "",
            "# Stage 2: stage 1's fitted linear predictor becomes stage 2's offset,",
            "# exactly as in the two-stage SMR/SHR pattern.",
            f"xbeta <- as.matrix(d[, c({cov_str})]) %*% coef(fit1)"
            + (f" + d${stage1.offset}" if stage1.offset else ""),
            "d$.xbeta <- as.numeric(xbeta)",
            'write.csv(data.frame(xbeta=d$.xbeta), file.path(results_dir, "xbeta.csv"), row.names=FALSE)',
            f'fit2 <- coxph({_r_surv_call(stage2)} ~ {_r_formula_rhs(stage2, ".xbeta")}, data=d,',
            f'              ties="{ties}"' + (f", weights={stage2.sample_weight}" if stage2.sample_weight else "") + ")",
            "print(summary(fit2))",
            f'write_result(fit2, "stage2", has_strata={"TRUE" if stage2.strata else "FALSE"})',
        ]

    lines.append('\ncat("R reference results written to", results_dir, "\\n")')
    return "\n".join(lines)


def _load_data(path: str) -> pd.DataFrame:
    if path.endswith(".parquet"):
        return pd.read_parquet(path)
    return pd.read_csv(path)


def _compare_coefficients(py_model: CoxPH, r_coef_path: str, rtol: float = 1e-4) -> List[str]:
    lines = []
    if not os.path.exists(r_coef_path) or py_model.n_features_in_ == 0:
        return lines
    r = pd.read_csv(r_coef_path)
    py_coef = py_model.coef_
    if len(r) != len(py_coef):
        lines.append(f"  [MISMATCH] R has {len(r)} coefficient(s), Python has {len(py_coef)}")
        return lines
    for name, pc, rc, pse, rse in zip(
        py_model.feature_names_in_, py_coef, r["coef"], py_model.standard_errors_, r["se_coef"]
    ):
        rel_c = abs(pc - rc) / max(abs(rc), 1e-8)
        rel_s = abs(pse - rse) / max(abs(rse), 1e-8)
        status = "OK" if rel_c < rtol and rel_s < rtol else "CHECK"
        lines.append(
            f"  [{status}] {name}: coef py={pc:.6g} r={rc:.6g} (rel diff {rel_c:.2e}); "
            f"se py={pse:.6g} r={rse:.6g} (rel diff {rel_s:.2e})"
        )
    return lines


def _compare_loglik(py_loglik: float, r_meta_path: str, rtol: float = 1e-5) -> str:
    if not os.path.exists(r_meta_path):
        return ""
    meta = pd.read_csv(r_meta_path)
    r_ll = float(meta["loglik_beta"].iloc[0])
    rel = abs(py_loglik - r_ll) / max(abs(r_ll), 1e-8)
    status = "OK" if rel < rtol else "CHECK"
    return f"  [{status}] log-likelihood: py={py_loglik:.6f} r={r_ll:.6f} (rel diff {rel:.2e})"


def _compare_baseline(py_baseline: pd.DataFrame, r_baseline_path: str, rtol: float = 1e-3) -> List[str]:
    lines = []
    if not os.path.exists(r_baseline_path):
        return lines
    rb = pd.read_csv(r_baseline_path)
    if "strata" in rb.columns and rb["strata"].nunique() > 1:
        rb = rb.rename(columns={"strata": "stratum"})
        rb["stratum"] = rb["stratum"].astype(str).str.extract(r"(-?\d+)$")[0]
        py = py_baseline.copy()
        py["stratum"] = py["stratum"].astype(str)
        merged = pd.merge(py, rb, on=["stratum", "time"], suffixes=("_py", "_r"))
    else:
        merged = pd.merge(py_baseline, rb, on="time", suffixes=("_py", "_r"))
    if merged.empty:
        lines.append("  [WARNING] no overlapping (stratum, time) rows between Python and R baseline hazard -- check stratum labeling")
        return lines
    diffs = (merged["hazard_py"] - merged["hazard_r"]).abs() / merged["hazard_r"].abs().clip(lower=1e-8)
    n_bad = int((diffs > rtol).sum())
    status = "OK" if n_bad == 0 else "CHECK"
    lines.append(
        f"  [{status}] baseline hazard: {len(merged)} matched time points, "
        f"max rel diff {diffs.max():.2e}, {n_bad} point(s) over {rtol:.0e} tolerance"
    )
    return lines


def run_validation(spec_path: str, r_results_override: Optional[str] = None) -> str:
    with open(spec_path) as f:
        spec = json.load(f)

    data_path = spec["data"]
    ties = spec.get("ties", "breslow")
    output_dir = spec.get("output_dir", "validation_output")
    os.makedirs(output_dir, exist_ok=True)

    stage1 = StageSpec.from_dict(spec["stage1"])
    stage2_raw = spec.get("stage2")
    stage2 = None
    if stage2_raw is not None:
        stage2 = StageSpec.from_dict(stage2_raw)
        # Stage 2 reuses stage 1's survival object unless explicitly overridden.
        for f_ in ("start", "stop", "duration", "event"):
            if getattr(stage2, f_) is None:
                setattr(stage2, f_, getattr(stage1, f_))

    report = [f"Validation run for spec: {spec_path}", f"Data: {data_path}", f"Ties: {ties}", ""]

    df = _load_data(data_path)

    pf1 = preflight_report(
        df, covariates=stage1.covariates, event=stage1.event, duration=stage1.duration,
        start=stage1.start, stop=stage1.stop, strata=stage1.strata, offset=stage1.offset,
        sample_weight=stage1.sample_weight,
    )
    report.append(pf1.report(label="stage 1"))
    if pf1.fatal:
        report.append(
            "\nStopping before fitting: resolve the fatal issue(s) above first "
            "(CoxPH.fit() would raise on the same data)."
        )
        return "\n".join(report)

    model1 = _fit_python(df, stage1, ties)
    report.append(
        f"\nPython stage 1 fit: converged={model1.converged_} n_iter={model1.n_iter_} "
        f"n_obs={model1.n_obs_} n_events={model1.n_events_} loglik={model1.log_likelihood_:.6f}"
    )

    model2 = None
    if stage2 is not None:
        pf2 = preflight_report(
            df, covariates=stage2.covariates, event=stage2.event, duration=stage2.duration,
            start=stage2.start, stop=stage2.stop, strata=stage2.strata,
            sample_weight=stage2.sample_weight,
        )
        report.append("\n" + pf2.report(label="stage 2"))
        if pf2.fatal:
            report.append("\nStopping before stage 2: resolve the fatal issue(s) above first.")
            return "\n".join(report)
        xbeta = model1.predict_linear(
            df[stage1.covariates] if stage1.covariates else pd.DataFrame(index=df.index),
            offset=df[stage1.offset] if stage1.offset else None,
        )
        model2 = _fit_python(df, stage2, ties, offset_override=xbeta)
        report.append(
            f"Python stage 2 fit: converged={model2.converged_} n_iter={model2.n_iter_} "
            f"n_obs={model2.n_obs_} n_events={model2.n_events_} loglik={model2.log_likelihood_:.6f}"
        )

    r_script = generate_r_script(
        os.path.abspath(data_path), stage1, ties, stage2=stage2,
        results_dir=os.path.join(os.path.abspath(output_dir), "r_results"),
    )
    r_script_path = os.path.join(output_dir, "run_all_check.R")
    with open(r_script_path, "w") as f:
        f.write(r_script)
    report.append(f"\nGenerated R comparison script: {r_script_path}")

    r_results_dir = os.path.join(output_dir, "r_results")

    if r_results_override is not None:
        r_results_dir = r_results_override
        report.append(f"Using pre-computed R results from: {r_results_dir}")
    elif shutil.which("Rscript") is None:
        report.append(
            "R (Rscript) not found in this environment -- skipping the R-side fit. "
            f"Copy '{r_script_path}' to a machine with R + the survival package "
            "installed and run it there (`Rscript run_all_check.R`), copy the "
            f"resulting '{os.path.join(output_dir, 'r_results')}' directory back, "
            "and re-run this tool with "
            f"`--spec {spec_path} --r-results <path to that copied directory>` "
            "to complete the comparison without needing R here at all."
        )
        return "\n".join(report)
    else:
        proc = subprocess.run(["Rscript", r_script_path], capture_output=True, text=True)
        report.append("\n--- R output ---")
        report.append(proc.stdout)
        if proc.returncode != 0:
            report.append("[R script FAILED]")
            report.append(proc.stderr)
            return "\n".join(report)

    report.append("\n--- Comparison: stage 1 ---")
    report += _compare_coefficients(model1, os.path.join(r_results_dir, "stage1_coefficients.csv"))
    ll_line = _compare_loglik(model1.log_likelihood_, os.path.join(r_results_dir, "stage1_meta.csv"))
    if ll_line:
        report.append(ll_line)
    report += _compare_baseline(model1.baseline_hazard_, os.path.join(r_results_dir, "stage1_baseline.csv"))

    if model2 is not None:
        report.append("\n--- Comparison: stage 2 ---")
        report += _compare_coefficients(model2, os.path.join(r_results_dir, "stage2_coefficients.csv"))
        ll_line = _compare_loglik(model2.log_likelihood_, os.path.join(r_results_dir, "stage2_meta.csv"))
        if ll_line:
            report.append(ll_line)
        report += _compare_baseline(model2.baseline_hazard_, os.path.join(r_results_dir, "stage2_baseline.csv"))

    return "\n".join(report)


def main():
    parser = argparse.ArgumentParser(
        description="Validate coxph.CoxPH against real R output on your own data."
    )
    parser.add_argument("--spec", required=True, help="Path to a JSON model spec (see EXAMPLE_SPEC in this module).")
    parser.add_argument(
        "--r-results", default=None, dest="r_results",
        help="Path to a directory of pre-computed R results (from running the "
             "generated run_all_check.R on a different machine) -- use this to "
             "complete the comparison without needing R installed here.",
    )
    parser.add_argument("--report-out", default=None, help="Where to write the text report (default: <output_dir>/report.txt).")
    args = parser.parse_args()

    report = run_validation(args.spec, r_results_override=args.r_results)
    print(report)

    with open(args.spec) as f:
        spec = json.load(f)
    output_dir = spec.get("output_dir", "validation_output")
    os.makedirs(output_dir, exist_ok=True)
    report_path = args.report_out or os.path.join(output_dir, "report.txt")
    with open(report_path, "w") as f:
        f.write(report)
    print(f"\n(Report also written to {report_path})")


if __name__ == "__main__":
    main()
