#!/usr/bin/env Rscript
# Fits survival::coxph() on each of the shared synthetic datasets in
# r_reference/data/ (generated by generate_data.py) and writes results to
# r_reference/results/*.csv for the Python test suite to compare against.
#
# This is the actual ground truth the Python implementation is validated
# against -- not a synthetic stand-in -- so every number this script
# writes out is what R itself computed, not a hand-derived expectation.

suppressMessages(library(survival))

# Base directory (containing data/ and results/) is passed explicitly as
# a command-line arg, falling back to the current directory, rather than
# relying on Rscript's inconsistent introspection of its own script path.
args <- commandArgs(trailingOnly = TRUE)
base <- if (length(args) >= 1) args[[1]] else "."
datadir <- file.path(base, "data")
resultsdir <- file.path(base, "results")
dir.create(resultsdir, showWarnings = FALSE, recursive = TRUE)

write_coef_table <- function(fit, name) {
  s <- summary(fit)
  coefs <- as.data.frame(s$coefficients)
  ci <- as.data.frame(s$conf.int)
  out <- data.frame(
    term = rownames(coefs),
    coef = coefs[["coef"]],
    se_coef = coefs[, grep("^se\\(coef\\)$", colnames(coefs))],
    z = coefs[["z"]],
    p = coefs[, grep("^Pr", colnames(coefs))],
    lower_95 = ci[, 3],
    upper_95 = ci[, 4]
  )
  write.csv(out, file.path(resultsdir, paste0(name, "_coefficients.csv")), row.names = FALSE)

  meta <- data.frame(
    loglik_beta = fit$loglik[2],
    loglik_null = fit$loglik[1],
    n = fit$n,
    nevent = fit$nevent,
    n_iter = fit$iter
  )
  write.csv(meta, file.path(resultsdir, paste0(name, "_meta.csv")), row.names = FALSE)

  vcov_df <- as.data.frame(vcov(fit))
  colnames(vcov_df) <- rownames(coefs)
  write.csv(vcov_df, file.path(resultsdir, paste0(name, "_vcov.csv")), row.names = FALSE)
}

write_baseline <- function(fit, name, has_strata = FALSE) {
  bh <- basehaz(fit, centered = FALSE)
  if (!has_strata) bh$strata <- "0"
  write.csv(bh, file.path(resultsdir, paste0(name, "_baseline.csv")), row.names = FALSE)
}

write_residuals <- function(fit, name) {
  mart <- residuals(fit, type = "martingale")
  write.csv(data.frame(martingale = mart), file.path(resultsdir, paste0(name, "_residuals.csv")), row.names = FALSE)
}

cat("== basic ==\n")
d <- read.csv(file.path(datadir, "basic.csv"))
fit <- coxph(Surv(time, event) ~ x1 + x2 + x3, data = d, ties = "breslow")
print(summary(fit))
write_coef_table(fit, "basic")
write_baseline(fit, "basic")
write_residuals(fit, "basic")

cat("\n== left_truncation ==\n")
d <- read.csv(file.path(datadir, "left_truncation.csv"))
fit <- coxph(Surv(start, stop, event) ~ x1 + x2, data = d, ties = "breslow")
print(summary(fit))
write_coef_table(fit, "left_truncation")
write_baseline(fit, "left_truncation")
write_residuals(fit, "left_truncation")

cat("\n== strata ==\n")
d <- read.csv(file.path(datadir, "strata.csv"))
fit <- coxph(Surv(stop, event) ~ x1 + x2 + strata(provider), data = d, ties = "breslow")
print(summary(fit))
write_coef_table(fit, "strata")
write_baseline(fit, "strata", has_strata = TRUE)
write_residuals(fit, "strata")

cat("\n== offset ==\n")
d <- read.csv(file.path(datadir, "offset.csv"))
fit <- coxph(Surv(stop, event) ~ x1 + x2 + offset(log_exposure), data = d, ties = "breslow")
print(summary(fit))
write_coef_table(fit, "offset")
write_baseline(fit, "offset")
write_residuals(fit, "offset")

cat("\n== weights ==\n")
d <- read.csv(file.path(datadir, "weights.csv"))
fit <- coxph(Surv(stop, event) ~ x1 + x2, data = d, weights = weight, ties = "breslow")
print(summary(fit))
write_coef_table(fit, "weights")
write_baseline(fit, "weights")
write_residuals(fit, "weights")

cat("\n== combined (strata + offset + weights + left truncation) ==\n")
d <- read.csv(file.path(datadir, "combined.csv"))
fit <- coxph(
  Surv(start, stop, event) ~ x1 + x2 + x3 + strata(provider) + offset(offset1),
  data = d, weights = weight, ties = "breslow"
)
print(summary(fit))
write_coef_table(fit, "combined")
write_baseline(fit, "combined", has_strata = TRUE)
write_residuals(fit, "combined")

cat("\n== two-stage (stage 1 estimates saved for stage 2 in Python) ==\n")
d <- read.csv(file.path(datadir, "combined.csv"))
stage1 <- coxph(
  Surv(start, stop, event) ~ x1 + x2 + x3 + strata(provider) + offset(offset1),
  data = d, weights = weight, ties = "breslow"
)
write_coef_table(stage1, "two_stage_1")
xbeta <- as.matrix(d[, c("x1", "x2", "x3")]) %*% coef(stage1) + d$offset1
d$xbeta <- as.numeric(xbeta)
stage2 <- coxph(
  Surv(start, stop, event) ~ offset(xbeta),
  data = d, weights = weight, ties = "breslow"
)
# stage 2 has no free coefficients -- what matters is its log-likelihood
# and baseline hazard (the SMR/SHR "observed vs expected" comparison),
# not a coefficient table.
meta <- data.frame(loglik = stage2$loglik[1], n = stage2$n, nevent = stage2$nevent)
write.csv(meta, file.path(resultsdir, "two_stage_2_meta.csv"), row.names = FALSE)
write_baseline(stage2, "two_stage_2")
write.csv(data.frame(xbeta = d$xbeta), file.path(resultsdir, "two_stage_xbeta.csv"), row.names = FALSE)

cat("\n== SMR two-stage (distinct covars1/covars2, no offset/weights in stage 1) ==\n")
d <- read.csv(file.path(datadir, "smr_two_stage.csv"))
smr_stage1 <- coxph(
  Surv(start, stop, event) ~ x1 + x2 + strata(provider),
  data = d, ties = "breslow"
)
print(summary(smr_stage1))
write_coef_table(smr_stage1, "smr_stage1")
xbeta_smr <- as.matrix(d[, c("x1", "x2")]) %*% coef(smr_stage1)
d$xbeta_smr <- as.numeric(xbeta_smr)
write.csv(data.frame(xbeta = d$xbeta_smr), file.path(resultsdir, "smr_xbeta.csv"), row.names = FALSE)

smr_stage2 <- coxph(
  Surv(start, stop, event) ~ z1 + offset(xbeta_smr),
  data = d, ties = "breslow"
)
print(summary(smr_stage2))
write_coef_table(smr_stage2, "smr_stage2")
write_baseline(smr_stage2, "smr_stage2")
write_residuals(smr_stage2, "smr_stage2")

cat("\n== basic (Efron ties -- R's own default) ==\n")
d <- read.csv(file.path(datadir, "basic.csv"))
fit <- coxph(Surv(time, event) ~ x1 + x2 + x3, data = d, ties = "efron")
print(summary(fit))
write_coef_table(fit, "basic_efron")
write_baseline(fit, "basic_efron")
write_residuals(fit, "basic_efron")

cat("\n== weights (Efron ties) -- also confirms fit$naive.var vs fit$var ==\n")
d <- read.csv(file.path(datadir, "weights.csv"))
fit <- coxph(Surv(stop, event) ~ x1 + x2, data = d, weights = weight, ties = "efron")
print(summary(fit))
write_coef_table(fit, "weights_efron")
write_baseline(fit, "weights_efron")
# naive.var is what summary()'s se(coef) column and this package's
# standard_errors_ both correspond to; var (and vcov()) is the ROBUST
# sandwich estimator once non-trivial weights are present -- see
# docs/R_COMPATIBILITY.md, Section 5b.
write.csv(data.frame(se_naive = sqrt(diag(fit$naive.var)), se_robust = sqrt(diag(fit$var))),
          file.path(resultsdir, "weights_efron_naive_vs_robust.csv"), row.names = FALSE)

cat("\n== strata + left truncation (Efron ties) ==\n")
d <- read.csv(file.path(datadir, "left_truncation.csv"))
fit <- coxph(Surv(start, stop, event) ~ x1 + x2, data = d, ties = "efron")
print(summary(fit))
write_coef_table(fit, "left_truncation_efron")
write_baseline(fit, "left_truncation_efron")
write_residuals(fit, "left_truncation_efron")

cat("\nAll R reference results written to", resultsdir, "\n")
